In [2]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
np.set_printoptions(precision=4)
import sys

In [3]:
ints = np.ones(10, dtype=np.uint16)

In [4]:
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [5]:
floats = np.ones(10, dtype=np.float32)

In [6]:
floats

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [7]:
np.issubdtype(ints.dtype, np.integer)

True

In [8]:
np.issubdtype(floats.dtype, np.floating)

True

In [9]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [10]:
arr = np.arange(8)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [13]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
arr = np.arange(15)

In [15]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
other_arr = np.ones((3, 5))

In [17]:
other_arr.shape

(3, 5)

In [18]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
arr = np.arange(15).reshape((5, 3))

In [20]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr = np.arange(12).reshape((3, 4))

In [24]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [27]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [28]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [29]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [31]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [33]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [35]:
from numpy.random import randn

In [36]:
arr = randn(5, 2)

In [37]:
arr

array([[-1.0022, -1.1704],
       [ 1.009 , -1.2423],
       [-0.3173, -1.347 ],
       [-1.1995, -0.8411],
       [-2.3323,  0.0066]])

In [38]:
first, second, third = np.split(arr, [1, 3])

In [39]:
first

array([[-1.0022, -1.1704]])

In [40]:
second

array([[ 1.009 , -1.2423],
       [-0.3173, -1.347 ]])

In [41]:
third

array([[-1.1995, -0.8411],
       [-2.3323,  0.0066]])

In [42]:
arr = np.arange(6)

In [43]:
arr1 = arr.reshape((3, 2))

In [44]:
arr2 = randn(3, 2)

In [45]:
np.r_[arr1, arr2]

array([[ 0.    ,  1.    ],
       [ 2.    ,  3.    ],
       [ 4.    ,  5.    ],
       [-0.1706,  2.1625],
       [-0.4549,  0.2342],
       [ 0.2635,  0.3143]])

In [46]:
np.c_[arr1, arr2]

array([[ 0.    ,  1.    , -0.1706,  2.1625],
       [ 2.    ,  3.    , -0.4549,  0.2342],
       [ 4.    ,  5.    ,  0.2635,  0.3143]])

In [47]:
np.c_[10:30, 23:43]

array([[10, 23],
       [11, 24],
       [12, 25],
       [13, 26],
       [14, 27],
       [15, 28],
       [16, 29],
       [17, 30],
       [18, 31],
       [19, 32],
       [20, 33],
       [21, 34],
       [22, 35],
       [23, 36],
       [24, 37],
       [25, 38],
       [26, 39],
       [27, 40],
       [28, 41],
       [29, 42]])

In [48]:
arr = np.arange(3)

In [49]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [50]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [51]:
arr = randn(2, 2)

In [52]:
arr

array([[ 0.8694,  0.4405],
       [ 0.627 , -2.1061]])

In [53]:
arr.repeat(2, axis=0)

array([[ 0.8694,  0.4405],
       [ 0.8694,  0.4405],
       [ 0.627 , -2.1061],
       [ 0.627 , -2.1061]])

In [54]:
arr.repeat(2, axis=1)

array([[ 0.8694,  0.8694,  0.4405,  0.4405],
       [ 0.627 ,  0.627 , -2.1061, -2.1061]])

In [55]:
arr.repeat([2, 3], axis=0)

array([[ 0.8694,  0.4405],
       [ 0.8694,  0.4405],
       [ 0.627 , -2.1061],
       [ 0.627 , -2.1061],
       [ 0.627 , -2.1061]])

In [56]:
arr.repeat([2, 3], axis=1)

array([[ 0.8694,  0.8694,  0.4405,  0.4405,  0.4405],
       [ 0.627 ,  0.627 , -2.1061, -2.1061, -2.1061]])

In [57]:
arr

array([[ 0.8694,  0.4405],
       [ 0.627 , -2.1061]])

In [58]:
np.tile(arr, 2)

array([[ 0.8694,  0.4405,  0.8694,  0.4405],
       [ 0.627 , -2.1061,  0.627 , -2.1061]])

In [59]:
arr

array([[ 0.8694,  0.4405],
       [ 0.627 , -2.1061]])

In [60]:
np.tile(arr, (2, 1))

array([[ 0.8694,  0.4405],
       [ 0.627 , -2.1061],
       [ 0.8694,  0.4405],
       [ 0.627 , -2.1061]])

In [61]:
np.tile(arr, (3, 2))

array([[ 0.8694,  0.4405,  0.8694,  0.4405],
       [ 0.627 , -2.1061,  0.627 , -2.1061],
       [ 0.8694,  0.4405,  0.8694,  0.4405],
       [ 0.627 , -2.1061,  0.627 , -2.1061],
       [ 0.8694,  0.4405,  0.8694,  0.4405],
       [ 0.627 , -2.1061,  0.627 , -2.1061]])

In [62]:
arr = np.arange(10) * 100

In [63]:
inds = [7, 1, 2, 6]

In [64]:
arr[inds]

array([700, 100, 200, 600])

In [65]:
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [66]:
arr.take(inds)

array([700, 100, 200, 600])

In [67]:
arr.put(inds, 43)

In [68]:
arr

array([  0,  43,  43, 300, 400, 500,  43,  43, 800, 900])

In [69]:
arr.put(inds, [40, 12, 423, 5])

In [70]:
arr

array([  0,  12, 423, 300, 400, 500,   5,  40, 800, 900])

In [71]:
inds = [2, 0, 2, 1]

In [72]:
arr = randn(2, 4)

In [73]:
arr

array([[ 0.8299, -0.1796,  0.7359,  0.2147],
       [-0.167 , -1.3422,  0.2035, -0.6458]])

In [74]:
arr.take(inds, axis=1)

array([[ 0.7359,  0.8299,  0.7359, -0.1796],
       [ 0.2035, -0.167 ,  0.2035, -1.3422]])

In [75]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [76]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [77]:
arr = randn(4, 3)

In [78]:
arr.mean(0)

array([-0.1496, -1.2305,  0.1851])

In [79]:
arr

array([[-0.4103, -1.0482, -0.192 ],
       [-0.2772, -1.8442,  0.1682],
       [ 0.9353, -1.1021,  0.1488],
       [-0.8463, -0.9274,  0.6152]])

In [80]:
arr.mean(1)

array([-0.5502, -0.6511, -0.006 , -0.3862])

In [81]:
demeaned = arr - arr.mean(0)

In [82]:
demeaned

array([[-0.2607,  0.1823, -0.3771],
       [-0.1276, -0.6137, -0.0168],
       [ 1.085 ,  0.1284, -0.0363],
       [-0.6967,  0.303 ,  0.4302]])

In [83]:
demeaned.mean(1)

array([-0.1518, -0.2527,  0.3924,  0.0122])

In [84]:
arr

array([[-0.4103, -1.0482, -0.192 ],
       [-0.2772, -1.8442,  0.1682],
       [ 0.9353, -1.1021,  0.1488],
       [-0.8463, -0.9274,  0.6152]])

In [85]:
row_means = arr.mean(1)

In [86]:
row_means.reshape((4, 1))

array([[-0.5502],
       [-0.6511],
       [-0.006 ],
       [-0.3862]])

In [87]:
demeaned = arr - row_means.reshape((4, 1))

In [88]:
demeaned.mean(1)

array([ -7.4015e-17,   0.0000e+00,   1.8504e-17,   0.0000e+00])

In [90]:
arr - arr.mean(0)

array([[-0.2607,  0.1823, -0.3771],
       [-0.1276, -0.6137, -0.0168],
       [ 1.085 ,  0.1284, -0.0363],
       [-0.6967,  0.303 ,  0.4302]])

In [91]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.1398, -0.498 ,  0.3582],
       [ 0.3738, -1.1931,  0.8193],
       [ 0.9413, -1.0961,  0.1548],
       [-0.4601, -0.5413,  1.0014]])

In [92]:
arr = np.zeros((4, 4))

In [93]:
arr_3d = arr[:, np.newaxis, :]

In [94]:
arr_3d.shape

(4, 1, 4)

In [95]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [96]:
arr_3d

array([[[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]]])

In [97]:
arr_1d = np.random.normal(size=3)

In [98]:
arr_1d[:, np.newaxis]

array([[ 1.2239],
       [ 1.1244],
       [ 0.547 ]])

In [99]:
arr_1d[np.newaxis, :]

array([[ 1.2239,  1.1244,  0.547 ]])

In [100]:
arr = randn(3, 4, 5)

In [101]:
depth_means = arr.mean(2)

In [102]:
depth_means

array([[-0.0544,  0.2605, -0.024 ,  0.9545],
       [-0.7665, -0.1499, -0.7825, -0.0888],
       [ 0.6149,  0.5023, -0.5118, -0.3834]])

In [103]:
demeaned = arr - depth_means[:, :, np.newaxis]

In [104]:
demeaned.mean(2)

array([[ -1.6653e-17,   0.0000e+00,   4.4409e-17,  -4.4409e-17],
       [ -4.4409e-17,   0.0000e+00,   0.0000e+00,  -1.1102e-17],
       [  0.0000e+00,   8.8818e-17,   6.6613e-17,   0.0000e+00]])

In [105]:
arr = np.zeros((4, 3))

In [106]:
arr[:] = 5

In [107]:
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [108]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [109]:
arr[:] = col[:, np.newaxis]

In [110]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [111]:
arr[:2] = [[-1.37], [0.509]]

In [112]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [113]:
arr = np.arange(10)

In [114]:
np.add.reduce(arr)

45

In [115]:
arr.sum()

45

In [116]:
arr = randn(5, 5)

In [117]:
arr[::2].sort(1)

In [118]:
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [119]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [120]:
np.all(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [121]:
arr = np.arange(15).reshape((3, 5))

In [122]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [123]:
arr = np.arange(3).repeat([1, 2, 2])

In [124]:
arr

array([0, 1, 1, 2, 2])

In [125]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [126]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [127]:
result = np.subtract.outer(randn(3, 4), randn(5))

In [128]:
result.shape

(3, 4, 5)

In [129]:
arr = np.arange(10)

In [130]:
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [131]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
arr = np.multiply.outer(np.arange(4), np.arange(5))

In [133]:
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [134]:
brr = np.multiply.outer(np.arange(5), np.arange(4))

In [135]:
brr

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  3],
       [ 0,  2,  4,  6],
       [ 0,  3,  6,  9],
       [ 0,  4,  8, 12]])

In [136]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

In [137]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [138]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.])

In [139]:
arr = randn(10000)

In [140]:
%timeit add_them(arr, arr)

1000 loops, best of 3: 1.8 ms per loop


In [141]:
%timeit np.add(arr, arr)

The slowest run took 16.78 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 4.57 µs per loop


In [142]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5, 6), (3.141592653589793, -2)], 
      dtype=[('x', '<f8'), ('y', '<i4')])

In [143]:
dtype

[('x', numpy.float64), ('y', numpy.int32)]

In [144]:
sarr[0]

(1.5, 6)

In [145]:
sarr[1]

(3.141592653589793, -2)

In [146]:
sarr[1]['x']

3.1415926535897931

In [147]:
sarr[0]['y']

6

In [148]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)], 
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [149]:
arr[0]['x']

array([0, 0, 0])

In [150]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [151]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']
data['y']
data['x']['a']

array([ 1.,  3.])

In [152]:
arr = randn(6)

In [153]:
arr.sort()

In [154]:
arr

array([-1.66  ,  0.0959,  0.6752,  1.0866,  1.2155,  1.2187])

In [155]:
arr = randn(3, 5)

In [156]:
arr

array([[ 0.2406, -0.9033, -1.0711,  1.0333, -0.4271],
       [ 0.2383, -0.8526,  0.6407,  2.7461, -0.2006],
       [-0.2154,  0.1485,  0.7506,  0.1581,  0.7835]])

In [157]:
arr[:, 0].sort()

In [158]:
arr

array([[-0.2154, -0.9033, -1.0711,  1.0333, -0.4271],
       [ 0.2383, -0.8526,  0.6407,  2.7461, -0.2006],
       [ 0.2406,  0.1485,  0.7506,  0.1581,  0.7835]])

In [159]:
arr = randn(3, 5)

In [160]:
arr

array([[ 0.1063,  0.4757,  0.0186,  0.1879,  1.4446],
       [-1.6082,  1.573 , -0.4724,  1.5929,  1.4576],
       [ 0.767 ,  0.2335, -0.7196,  0.652 , -0.6135]])

In [161]:
arr.sort(axis=1)

In [162]:
arr

array([[ 0.0186,  0.1063,  0.1879,  0.4757,  1.4446],
       [-1.6082, -0.4724,  1.4576,  1.573 ,  1.5929],
       [-0.7196, -0.6135,  0.2335,  0.652 ,  0.767 ]])

In [163]:
arr

array([[ 0.0186,  0.1063,  0.1879,  0.4757,  1.4446],
       [-1.6082, -0.4724,  1.4576,  1.573 ,  1.5929],
       [-0.7196, -0.6135,  0.2335,  0.652 ,  0.767 ]])

In [164]:
arr[:, ::-1]

array([[ 1.4446,  0.4757,  0.1879,  0.1063,  0.0186],
       [ 1.5929,  1.573 ,  1.4576, -0.4724, -1.6082],
       [ 0.767 ,  0.652 ,  0.2335, -0.6135, -0.7196]])

In [165]:
values = np.array([5, 0, 1, 3, 2])

In [166]:
indexer = values.argsort()

In [167]:
indexer

array([1, 2, 4, 3, 0])

In [168]:
values[indexer]

array([0, 1, 2, 3, 5])

In [169]:
arr = randn(3, 5)
arr[0] = values
arr

array([[ 5.    ,  0.    ,  1.    ,  3.    ,  2.    ],
       [-0.0159, -0.1096, -0.8849, -1.1868,  1.2686],
       [-0.686 ,  1.7659, -0.0263,  1.2111, -0.5386]])

In [170]:
arr[:, arr[0].argsort()]

array([[ 0.    ,  1.    ,  2.    ,  3.    ,  5.    ],
       [-0.1096, -0.8849,  1.2686, -1.1868, -0.0159],
       [ 1.7659, -0.0263, -0.5386,  1.2111, -0.686 ]])

In [171]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

In [172]:
sorter

array([1, 2, 3, 0, 4])

In [173]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])

In [174]:
key = np.array([2, 2, 1, 1, 1])

In [175]:
indexer = key.argsort(kind='mergesort')

In [176]:
indexer

array([2, 3, 4, 0, 1])

In [177]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'], 
      dtype='|S8')

In [178]:
arr = np.array([0, 1, 7, 12, 15])

In [179]:
arr.searchsorted(9)

3

In [180]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [182]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])

In [183]:
arr.searchsorted([0, 1])

array([0, 3])

In [184]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [185]:
data = np.floor(np.random.uniform(0, 10000, size=50))

In [186]:
bins = np.array([0, 100, 1000, 5000, 10000])

In [187]:
data

array([ 3321.,  2737.,  6233.,  4013.,  7162.,  2765.,  5194.,  1562.,
        3130.,  5524.,  5330.,  1403.,  6265.,  8914.,  6317.,  6390.,
        4722.,  8404.,  1520.,  3523.,  6981.,  3710.,  1630.,   648.,
        2927.,  7652.,  1278.,   617.,  4576.,  2522.,  7704.,  5820.,
        1240.,  9124.,  9249.,  9650.,  1634.,  8221.,  7379.,  1096.,
        8599.,  3233.,  1865.,    75.,  1645.,  4096.,  4281.,   636.,
        7035.,  7185.])

In [188]:
len(data)

50

In [189]:
labels = bins.searchsorted(data)

In [190]:
labels

array([3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 4, 3, 4, 4, 4, 4, 3, 4, 3, 3, 4, 3, 3,
       2, 3, 4, 3, 2, 3, 3, 4, 4, 3, 4, 4, 4, 3, 4, 4, 3, 4, 3, 3, 1, 3, 3,
       3, 2, 4, 4])

In [191]:
Series(data).groupby(labels).mean()

1      75.000000
2     633.666667
3    2684.541667
4    7287.818182
dtype: float64

In [192]:
np.digitize(data, bins)

array([3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 4, 3, 4, 4, 4, 4, 3, 4, 3, 3, 4, 3, 3,
       2, 3, 4, 3, 2, 3, 3, 4, 4, 3, 4, 4, 4, 3, 4, 4, 3, 4, 3, 3, 1, 3, 3,
       3, 2, 4, 4])

In [193]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])
X[:, 0]  # one-dimensional
y = X[:, :1]  # two-dimensional by slicing
X
y

array([[ 8.8277],
       [ 3.8222],
       [-1.1428],
       [ 2.0441]])

In [194]:
np.dot(y.T, np.dot(X, y))

array([[ 1195.468]])

In [195]:
Xm = np.matrix(X)

In [196]:
ym = Xm[:, 0]

In [197]:
Xm

matrix([[ 8.8277,  3.8222, -1.1428,  2.0441],
        [ 3.8222,  6.7527,  0.8391,  2.0829],
        [-1.1428,  0.8391,  5.0169,  0.7957],
        [ 2.0441,  2.0829,  0.7957,  6.241 ]])

In [198]:
ym

matrix([[ 8.8277],
        [ 3.8222],
        [-1.1428],
        [ 2.0441]])

In [199]:
ym.T * Xm * ym

matrix([[ 1195.468]])

In [200]:
Xm.I * X

matrix([[  1.0000e+00,   1.8041e-16,  -6.2450e-17,   5.5511e-17],
        [ -6.9389e-17,   1.0000e+00,   6.9389e-18,  -8.3267e-17],
        [  1.1102e-16,   1.3878e-17,   1.0000e+00,   0.0000e+00],
        [  5.5511e-17,   1.1102e-16,   0.0000e+00,   1.0000e+00]])

In [201]:
ym = Xm[:, 0]

In [202]:
ym

matrix([[ 8.8277],
        [ 3.8222],
        [-1.1428],
        [ 2.0441]])

In [203]:
ym.T * Xm * ym

matrix([[ 1195.468]])

In [204]:
Xm.I * X

matrix([[  1.0000e+00,   1.8041e-16,  -6.2450e-17,   5.5511e-17],
        [ -6.9389e-17,   1.0000e+00,   6.9389e-18,  -8.3267e-17],
        [  1.1102e-16,   1.3878e-17,   1.0000e+00,   0.0000e+00],
        [  5.5511e-17,   1.1102e-16,   0.0000e+00,   1.0000e+00]])

In [205]:
Xm.I * Xm

matrix([[  1.0000e+00,   1.8041e-16,  -6.2450e-17,   5.5511e-17],
        [ -6.9389e-17,   1.0000e+00,   6.9389e-18,  -8.3267e-17],
        [  1.1102e-16,   1.3878e-17,   1.0000e+00,   0.0000e+00],
        [  5.5511e-17,   1.1102e-16,   0.0000e+00,   1.0000e+00]])

In [206]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))

In [207]:
section = mmap[:5]

In [208]:
section[:] = np.random.randn(5, 10000)

In [209]:
mmap.flush()

In [210]:
mmap

memmap([[ 0.2671,  0.2821,  0.3407, ...,  0.7829,  0.2668, -1.1721],
       [-0.8289, -0.6989,  0.6633, ..., -0.1062, -0.0367,  0.7169],
       [ 1.7301, -1.7863, -0.4022, ..., -2.0937, -0.6936,  2.4306],
       ..., 
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

In [211]:
del mmap

In [212]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))

In [213]:
mmap

memmap([[ 0.2671,  0.2821,  0.3407, ...,  0.7829,  0.2668, -1.1721],
       [-0.8289, -0.6989,  0.6633, ..., -0.1062, -0.0367,  0.7169],
       [ 1.7301, -1.7863, -0.4022, ..., -2.0937, -0.6936,  2.4306],
       ..., 
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

In [214]:
%xdel mmap

In [215]:
!rm mymmap

In [216]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
arr_c.flags
arr_f.flags
arr_f.flags.f_contiguous

True

In [217]:
%timeit arr_c.sum(1)
%timeit arr_f.sum(1)

1000 loops, best of 3: 631 µs per loop
1000 loops, best of 3: 634 µs per loop


In [218]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [219]:
arr_c[:50].flags.contiguous
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [220]:
%xdel arr_c
%xdel arr_f
%cd ..

/home/sennhviwang/python/data_process
